### ISSUE TITLE
Provisioning Apache 2.4 throws an error about mod_proxy_fdpass

### ISSUE THREAD

**Issue by steadweb** [iuscommunity-pkg/httpd24u#10]
Provisioned 2 boxes today and the same error has occurred:

```
FAILED! => {"changed": false, "failed": true, "msg": "httpd: Syntax error on line 56 of /etc/httpd/conf/httpd.conf: Syntax error on line 12 of /etc/httpd/conf.modules.d/00-proxy.conf: Cannot load modules/mod_proxy_fdpass.so into server: /etc/httpd/modules/mod_proxy_fdpass.so: cannot open shared object file: No such file or directory\n"}
```

Within the changelog:

```
changelog
* Fri Jul 22 2016 Carl George <carl.george@rackspace.com> - 2.4.23-2.ius
- Restore build of mod_proxy_fdpass (Fedora)
```

**Comment by carlwgeorge** [comment]
Thanks for the heads up @steadweb.  Someone brought this up in our IRC channel early this morning.  In the previous version the fdpass module was built by default, but starting in version 2.4.23 you must explicitly ask for it with the `--enable-proxy-fdpass` flag.  This affected Fedora as well, so we just [imported](https://github.com/iuscommunity-pkg/httpd24u/commit/66769962d8719924e881eb6a9cb1e4da98215f01) [their fix](http://pkgs.fedoraproject.org/cgit/rpms/httpd.git/diff/?id=53f8164b15d222388a1ce249d3935d8d11b26e40) into our spec file.

The new [2.4.23-2.ius build](https://github.com/iuscommunity-pkg/httpd24u/releases/tag/2.4.23-2.ius) has completed, and the automation to push it to the stable repository is already in progress.  That will complete in roughtly 8-9 hours from now and then the update will be available on our master mirror.  It will take a bit longer for the new package to propagate through the rest of the mirror network.  Short term, you can just comment out the `LoadModule proxy_fdpass_module modules/mod_proxy_fdpass.so` line in `/etc/httpd/conf.modules.d/00-proxy.conf`, and that will allow the service to start.

Sorry for the inconvenience!  If you would like to help us catch problems like this sooner, consider enabling our [testing repository](https://ius.io/Contributing/#early-testing) in a non-production environment.  This particular problematic release [(2.4.23-1.ius)](https://github.com/iuscommunity-pkg/httpd24u/releases/tag/2.4.23-1.ius) was first available in our testing repository on 2016-07-05.

**Comment by steadweb** [comment]
Thanks @carlwgeorge - really appreciated. Commenting out the line within `00-proxy.conf` was my solution :+1:

**Comment by carlwgeorge** [comment]
Closing the loop on this, the [2.4.23-2.ius build](https://github.com/iuscommunity-pkg/httpd24u/releases/tag/2.4.23-2.ius) moved to the stable repository as expected.
