### ISSUE TITLE
/etc/sysconfig/httpd ignored

### ISSUE THREAD

**Issue by rickschneider17** [iuscommunity-pkg/httpd24u#11]
it seems that the /etc/sysconfig/httpd file is not used by the package, as it is for other main EL7 packages, such as the one from CentOS 7. 
This can be worked around by creating a config through systemctl edit, but it is a difference in how the other httpd packages work.

the stock httpd systemd service file had this line, that httpd24u does not
EnvironmentFile=/etc/sysconfig/httpd

**Comment by b-harper** [comment]
Hey @rickschneider17 ,

Thanks for taking the time to chat on IRC and submit this bug.  I am able to confirm that httpd24u is not reading the /etc/sysconfig/httpd file it provides.  The stock httpd systemd service file includes the following line, not found in the httpd24u systemd service file:

EnvironmentFile=/etc/sysconfig/httpd

The IUS httpd24u package (like many IUS packages) was forked from Fedora.  [Fedora is looking for users to use systemd][0] and not the file within /etc/sysconfig/.  We will need to research to see if it is better for IUS packages to go full systemd or add the use of EnvironmentFile.

[0]: https://github.com/iuscommunity-pkg/httpd24u/blob/master/SOURCES/httpd.service#L5-L10

**Comment by b-harper** [comment]
I have been doing some digging regarding systemd service files and /etc/sysconfig files.  The [Overview of systemd for RHEL 7][0] has a Configuration files section states the following:

```
For systemd in RHEL 7, there are still files in /etc/sysconfig used to modify how services behave.
```
Fedora has an effort to [clean up systemd unit files][1], including /etc/sysconfig files. 

It would appear that /etc/sysconfig files are allowed as training wheels during the transition to systemd.  Once systemd is no longer new, the training wheels are removed.   I feel our packages should align with the Red Hat documentation and include the use of /etc/sysconfig files.  That being said, I would recommend embracing the systemd way as I would anticipate the use of /etc/sysconfig files will be going away at some point for EL. 

I will work on getting some updated packages built.



[0]: https://access.redhat.com/articles/754933
[1]: https://fedoraproject.org/wiki/Features/Systemd-unit-cleanup

**Comment by b-harper** [comment]
This change has been implemented.
