### ISSUE TITLE
Segmentationfault if SSLStaplingCache is enabled

### ISSUE THREAD

**Issue by raider700** [iuscommunity-pkg/httpd24u#14]
Hello,

we have a problem with the releases 2.4.25-2.ius and 2.4.25-3.ius with the function SSCStamplingCache. Basesystem is a minimal RHEL 7.3 and the apache is working as loadbalancer.

If the cache is enabled with the following line the graceful reload fails with a segmentation fault:
```
SSLStaplingCache shmcb:/run/httpd/stapling_cache(128000)
```

The message log contains after the graceful reload:
```
Mar 21 09:04:00 loadbalancer01 httpd: [Tue Mar 21 09:04:00.590046 2017] [core:warn] [pid 59575:tid 140170181482688] AH00111: Config variable ${woapp} is not defined
Mar 21 09:04:00 loadbalancer01 httpd: [Tue Mar 21 09:04:00.590201 2017] [core:warn] [pid 59575:tid 140170181482688] AH00111: Config variable ${woapp} is not defined
Mar 21 09:04:00 loadbalancer01 systemd[1]: Reloaded The Apache HTTP Server.
Mar 21 09:04:00 loadbalancer01 systemd-logind[738]: Removed session 43260.
Mar 21 09:04:01 loadbalancer01 systemd[1]: httpd.service: main process exited, code=killed, status=11/SEGV
Mar 21 09:04:01 loadbalancer01 shibd: INFO Shibboleth.Listener [8]: detected socket closure, shutting down worker thread
Mar 21 09:04:01 loadbalancer01 systemd[1]: Unit httpd.service entered failed state.
Mar 21 09:04:01 loadbalancer01 systemd[1]: httpd.service failed.
```

The apache error log contains:
```
Mar 21 09:04:00 loadbalancer01 httpd[31637]: [mpm_worker:notice] [vhost loadbalancer01.company.public] [pid 31637] [tid 31637] [err -] [ref -] AH00297: SIGUSR1 received.  Doing graceful restart
Mar 21 09:04:00 loadbalancer01 httpd[31637]: [Tue Mar 21 09:04:00.817482 2017] [core:warn] [pid 31637:tid 140398980937920] AH00111: Config variable ${woapp} is not defined
Mar 21 09:04:00 loadbalancer01 httpd[31637]: [Tue Mar 21 09:04:00.817504 2017] [core:warn] [pid 31637:tid 140398980937920] AH00111: Config variable ${woapp} is not defined
Mar 21 09:05:47 loadbalancer01 httpd[59802]: [Tue Mar 21 09:05:47.094735 2017] [core:notice] [pid 59802:tid 140495838210240] SELinux policy enabled; httpd running as context system_u:system_r:httpd_t:s0
Mar 21 09:05:47 loadbalancer01 httpd[59802]: [-:notice] [vhost loadbalancer01.company.public] [pid 59802] [tid 59802] [err -] [ref -] init: mod_aod revision 40096 compiled: Aug 24 2016 at 01:07:17; support threads = 1
Mar 21 09:05:47 loadbalancer01 httpd[59802]: [Tue Mar 21 09:05:47.495139 2017] [core:warn] [pid 59802:tid 140495838210240] AH00111: Config variable ${woapp} is not defined
Mar 21 09:05:47 loadbalancer01 httpd[59802]: [Tue Mar 21 09:05:47.495152 2017] [core:warn] [pid 59802:tid 140495838210240] AH00111: Config variable ${woapp} is not defined
Mar 21 09:05:47 loadbalancer01 httpd[59802]: [-:notice] [vhost loadbalancer01.company.public] [pid 59802] [tid 59802] [err -] [ref -] init: mod_aod revision 40096 compiled: Aug 24 2016 at 01:07:17; support threads = 1
Mar 21 09:05:47 loadbalancer01 httpd[59802]: [Tue Mar 21 09:05:47.673897 2017] [core:warn] [pid 59802:tid 140495838210240] AH00098: pid file /run/httpd/httpd.pid overwritten -- Unclean shutdown of previous Apache run?
Mar 21 09:05:47 loadbalancer01 httpd[59802]: [mpm_worker:notice] [vhost loadbalancer01.company.public] [pid 59802] [tid 59802] [err -] [ref -] AH00292: Apache/2.4.25 (Red Hat) OpenSSL/1.0.1e-fips configured -- resuming normal operations
Mar 21 09:05:47 loadbalancer01 httpd[59802]: [core:notice] [vhost loadbalancer01.company.public] [pid 59802] [tid 59802] [err -] [ref -] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
```

Are some additional informations needet?

Kindly regards,
Raider700

**Comment by carlwgeorge** [comment]
Hello @raider700,

Thanks for reporting your issue.  Our goal is to first identify if this is a packaging error or an upstream bug.

* You specifically mentioned both 2.4.25-2 and 2.4.25-3.  What about 2.4.25 **-1**?  In other words, does this affect all 2.4.25 rpm releases?
* Can you reproduce this error on Fedora as well?
* Can you reproduce this on other distributions that have version 2.4.25?

If the answer to all of those questions is yes, then the issue should be [reported upstream](http://httpd.apache.org/bug_report.html).

**Comment by b-harper** [comment]
Hey @raider700,

I would also try a full restart.  When dealing with certificate related changes, httpd typically needs a full restart.

**Comment by raider700** [comment]
Hi @carlwgeorge @b-harper,

thank you for the replies. I have tested it with all the 25 versions and the behavior is the same.
A restart ist working but a reload fails and a new start is needed.

It showed out that had a mistake in the description from the first post.
The segfault on reload happens when the line is **disabled**.

To reproduce it:
1) Add the line to a existing configuration
```SSLStaplingCache shmcb:/run/httpd/stapling_cache(128000)```
2) Enable it with restart or reload
3) Disable the added line
4) Execute ```sudo apachectl configtest && sudo apachectl graceful ```

In the /var/log/message the segfault is logged and the httpd process stopped.
A "systemctl start httpd" after the segfault makes a working start.

At the moment i don't have access to a fedora installation but i will try to test it as soon as possible.

Kindly regards,
Raider700

**Comment by b-harper** [comment]
Hey @raider700,

Thanks for the update.  When you say 'reload', do you mean a graceful restart?  I ask as some people use that term to mean a full restart.  For some applications it does not matter, but with httpd there is a difference.

In step 4, if you use a full restart instead of a graceful, do you still get the segfault?

**Comment by raider700** [comment]
Hi @b-harper,

thanks for the reply. Yes, with reload i mean a graceful restart.
("apachectl graceful" or "systemctl reload httpd")

With an "systemctl restart httpd" the segfault did not happen in step 4.

Kindly regards,
Raider700

**Comment by b-harper** [comment]
@raider700,  thanks for the clarification.  Reading over the description of  [SSLStaplingCache ][0] and [SSLUseStapling][1],  I would assume a full restart would be needed.  That being said, there should be a more elegant way to deal with this situation than a seg fault.  


[0]: https://httpd.apache.org/docs/trunk/mod/mod_ssl.html#sslstaplingcache
[1]: https://httpd.apache.org/docs/trunk/mod/mod_ssl.html#sslusestapling

**Comment by raider700** [comment]
@b-harper, thank you for the info and your efforts.
We will make a ticked for that on apache.org soon.
