### ISSUE TITLE
Compile against openssl 1.0.2

### ISSUE THREAD

**Issue by sterndata** [iuscommunity-pkg/httpd24u#16]
Now that openssl-1.0.2 has appeared in the CentOS 7.4 repos (CR), httpd24u should be compiled to use  it so ALPN support can be added for http/2 sites.

**Comment by carlwgeorge** [comment]
The CR repo is not enabled by default.  Taking this action would break updates for the majority of CentOS IUS users.  We are already tracking the need to rebuild this for CentOS 7.4 (when officially released), as we already have for [RHEL 7.4](https://github.com/iuscommunity-pkg/httpd24u/commit/d6e97cff3aa2e6c7b46baa05c0ab0b5525a8a70f).

**Comment by b-harper** [comment]
CentOS 7.4 has been released.  Updated packages have been built and will hit the testing repository during tonight's automation run.

**Comment by sterndata** [comment]
Thank you and the entire IUS team!

**Comment by jsbodine** [comment]
is this the correct spot to be watching when this  is released? Kinda waiting on pins and needles for it (before rebuilding a bunch of servers and wanted to make sure this was the right spot. Thanks!

**Comment by b-harper** [comment]
@jsbodine,

Yes, we will update this issue when the updated CentOS packages will be moved into the stable repositories.  You can also keep any eye on the [releases][0].

[0]: https://github.com/iuscommunity-pkg/httpd24u/releases

**Comment by sterndata** [comment]
It's in the testing repo if you want to use it now.

**Comment by b-harper** [comment]
The updated CentOS packages will be moved into the stable repositories during tonight's automation run.
