### ISSUE TITLE
Build with module mod_md by default

### ISSUE THREAD

**Issue by andmikey** [iuscommunity-pkg/httpd24u#17]
It would be useful to add [mod_md](https://httpd.apache.org/docs/trunk/mod/mod_md.html) to the default build of httpd24u.

This would allow for automatic certificate issuance and renewal from Let's Encrypt with Apache without having to run a version compiled from the latest upstream. 

I am happy to test the package with this added support on CentOS7 / SL7.

**Comment by carlwgeorge** [comment]
I was reviewing the Fedora implementation of this module to implement in our package the same way.  It's not behaving as expected, so I opened a bug with them so see if a certain patch is necessary.  I'll follow up once that gets resolved.

https://bugzilla.redhat.com/show_bug.cgi?id=1563846

**Comment by andmikey** [comment]
Do we have any updates on this? The linked RedHat bug looks like it's been resolved.

**Comment by matyuvt** [comment]
I also join and please build module, thank you.

**Comment by carlwgeorge** [comment]
I took a stab at enabling this, but discovered that it won't work with the system curl version.

```
checking for curl version >= 7.50... FAILED
```

https://svn.apache.org/viewvc/httpd/httpd/tags/2.4.34/modules/md/config2.m4?view=markup#l102

Replacing a critical system library like curl is not something the project is interested in tackling, so we won't be implementing mod_md in httpd24u.
