### ISSUE TITLE
systemctl files not present

### ISSUE THREAD

**Issue by TrapoSAMA** [iuscommunity-pkg/httpd24u#18]
Hi!

Latest build httpd24u-2.4.33-1.ius dont include system files like:

/usr/lib/systemd/system/htcacheclean.service
/usr/lib/systemd/system/httpd.service
/usr/lib/systemd/system/httpd.socket
/usr/lib/tmpfiles.d/httpd.conf

missing simbolic link httpd.service -> /usr/lib/systemd/system/httpd.service and

systemctl enable httpd
httpd.service is not a native service, redirecting to /sbin/chkconfig.
Executing /sbin/chkconfig httpd on

Thx

**Comment by carlwgeorge** [comment]
Well that's embarrassing!  Looks like I accidentally removed the `%bcond_without systemd` / `%bcond_with systemd` definitions in 33dce1a27916867b0c03797cd5f06be176b53ecb while doing an unrelated change.  I'll get that fixed ASAP and pushed out to the repos.  Thanks for letting me know!

**Comment by carlwgeorge** [comment]
Fixed in [httpd24u-2.4.33-2](https://github.com/iuscommunity-pkg/httpd24u/releases/tag/2.4.33-2), which will go straight to the stable repos during tonight's automation.
