### ISSUE TITLE
Lost XFF in logs since update

### ISSUE THREAD

**Issue by fitou13** [iuscommunity-pkg/httpd24u#20]
Hi, I used apache behind a load-balancer since, Since I update the package, X-Forwarded-For Header disapear in apache logs.

**Comment by carlwgeorge** [comment]
I'm not aware that X-Forwarded-For is logged by default.  Have you customized the logging directives to accomplish this?  Does downgrading the package make it work again?  Can you reproduce the issue with stock httpd?  Are you using EL6 or EL7?

**Comment by carlwgeorge** [comment]
Closing due to lack of feedback.
