### ISSUE TITLE
Security vulnerabilities in http24u-2.4.37-1

### ISSUE THREAD

**Issue by damoclark** [iuscommunity-pkg/httpd24u#26]
hi @carlwgeorge 

Wondering if you might be able to update this and associated package/s to version 2.4.38?

This version has known security vulnerabilities:

https://httpd.apache.org/security/vulnerabilities_24.html

Cheers,
Damo.

**Comment by carlwgeorge** [comment]
Thanks for bringing this to my attention.  2.4.38 has fixes for one important vulnerability and two low vulnerabilities.

https://httpd.apache.org/security/vulnerabilities_24.html#2.4.38

I'll start work on getting httpd24u updated.

**Comment by carlwgeorge** [comment]
[httpd24u-2.4.38-1](https://github.com/iuscommunity-pkg/httpd24u/releases/tag/2.4.38-1) will move to the testing repos during tonight's automation.
