### ISSUE TITLE
http2 support and el7 support

### ISSUE THREAD

**Issue by mmckinst** [iuscommunity-pkg/httpd24u#5]
It would be great if this had support for the [http/2](https://http2.github.io/) protocol and was built for el7. Currently the httpd that comes with el7 does not support http/2.

I've begun the work needed to add http/2 and el7 support and should have a pull request tomorrow for it.

**Comment by mmckinst** [comment]
simple vagrant set up at https://github.com/mmckinst/httpd24u-el7-testing to test it

**Comment by b-harper** [comment]
Hey @mmckinst 

It was good chatting with you over IRC and thanks for taking the time to submit this issue and the pull requests.  As we mentioned in IRC, we typically package only newer major versions than what RHEL provides and are cautious when it comes to when it comes to minor versions.    While not that common, RHEL will bump both major and minor software versions within the life span of an OS release.  

A recent example where IUS packaged a minor version increase over RHEL and then RHEL bumped their version is openssl 1.0.1 (IUS package openssl10).  We had to make a [tough judgement call on what to do with our openssl10 packages][0].

We will need to look closely at this request and more than likely that won't happen till the new year.  

-Ben








[0]: https://lists.launchpad.net/ius-community/msg00804.html

**Comment by b-harper** [comment]
Hey @mmckinst 

I was able to start an initial investigation.  Currently, the mod_http2 module is [experimental][0].  Unfortunately, I do not feel this module is a good fit for IUS.  You could build this module as a stand alone package in a copr repo.

-Ben


[0]: http://httpd.apache.org/docs/2.4/mod/mod_http2.html

**Comment by mmckinst** [comment]
Regarding the versioning, openssl doesn't really follow a normal versioning scheme so it might be a bad comparison. But if you look at projects that do follow semantic versioning or something close to it, Red Hat never increases anything other than the patch version. EG: REHL 5 started with httpd 2.2.x, MySQL 5.0.x, python 2.4.x, perl 5.8.x and is still on those versions. Apache won't be release a new httpd 2.6 any time soon and even if they do, its not like Red Hat will be adopting it for RHEL 7 the day its released.

Regarding the "experimental" status of mod_http2, it isn't enabled by default, but its there for people who want start offering the HTTP/2 protocol with the caveat being it is "subject to more change from release to release relative to other standard modules". FWIW, there are other "experimental" modules bundled with httpd24u right now: mod_lua and mod_allowmethods.

Demand for HTTP/2 is going to increase now that its a standard, I think adding HTTP/2 to EL7 for IUS would be a great addition for people who want to use a newer version than what Red Hat provides.

**Comment by carlwgeorge** [comment]
Regarding the "experimental" status of mod_http2, Fedora's httpd has it [enabled since October](http://pkgs.fedoraproject.org/cgit/rpms/httpd.git/commit/httpd.spec?id=91a2788bcecc45df329bd121a15ea7ec86285d82), so it's good enough for them.

Also worth noting, nghttp2 (a build requirement for this) was [submitted to epel-testing for EL6](https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2016-6963516bb0) a few days ago.  Once this is promoted to epel-stable we would be able to enable mod_http2 in httpd24u everywhere, rather than just in EL7.

**Comment by b-harper** [comment]
The nghttp2 package is now in EPEL6.  @mmckinst, can you update your PR and remove the conditionals for RHEL 7 so it can be built for RHEL 6 too.

**Comment by mmckinst** [comment]
pull request #6 updated. thanks guys!

**Comment by b-harper** [comment]
@mmckinst, thanks for updating the PR.  Adding http2 support looks fairly straight forward for EL 6, but adding httpd24u to EL 7 is a tad more complicated.  

There are build requirements for apr-devel and apr-util-devel of at least version 1.5.0.   EL 6 only comes with 1.3.9 for both apr-devel and apr-util-devel.  We typically like to build off base and not build a whole mess of dependencies.  We made an exception for httpd24u and created  apr15u and  apr15u-util.  El 7 provides apr-devel 1.4.8 and apr-util-devel 1.5.2.  IUS provides apr15u-devel  and apr15u-util-devel 1.5.2 fo EL 6.

There are a couple options for EL 7, none are perfect.  We could attempt to use stock  apr-util-devel  and build apr15u-devel.  That seems like it could get messy.  The other option is to just build both   apr15u-devel  and apr15u-util-devel for EL 7, even though EL 7 provides apr-util-devel 1.5.2.  That seems silly.  

While we look into EL 7 support, updated EL 6 httpd24u packages have been built and will hit the testing repositories after tonight's automation.

**Comment by carlwgeorge** [comment]
Another option is to completely deprecate apr15u and apr15u-util and instead use the bundled apr/apr-util libraries from the httpd tarball.  Currently we follow Fedora's practice of deleting those bundled libraries.  System libraries are generally favored over bundled libraries, but we have made exceptions in the past.

**Comment by mmckinst** [comment]
@b-harper I ran in to the same problem when I built httpd24u for el7. I ended up building apr15u and apr15u-util to get httpd24u to build. I can't remember if I had to modify the spec file at all but copr builds and src.rpms are at https://copr.fedorainfracloud.org/coprs/mmckinst/apr15u/ and https://copr.fedorainfracloud.org/coprs/mmckinst/apr15u-util/

**Comment by b-harper** [comment]
I misspoke regarding versions of apr-devel and apr-util-devel.  I think a chart will be easier to make sure I pass along correct information.

   | Required Version | Stock EL 6 | IUS EL 6 | Stock EL 7 | IUS EL 7
---|------------------------ | -------------- | ----------- | -------------- | ----------
apr-devel| >= 1.5.0 | 1.3.9 | 1.5.2 | 1.4.8 |    
apr-util-devel | >= 1.5.0 | 1.3.9 | 1.5.4 | 1.5.2 |    

This makes it some what less complicated.

**Comment by b-harper** [comment]
Some initial apr15u, apr-util and httpd24u packages have been built for EL 7 and will hit the testing after tonight's automation run. 

When it comes to the http2 support, is it something that should be enabled by default?  If so, should we follow Fedora's lead and put the configuration within 00-base.conf and not its own configuration file?  If it is something we do not want enabled by default, should we create a sub-package or just leave the configuration commented out?

**Comment by mmckinst** [comment]
The module should be loaded, but http2 shouldn't be enabled by default. It makes more sense to put it in 00-base.con like Fedora does. I don't think a subpackage is necessary and will just complicate things. 

Just loading the module doesn't enable HTTP/2 support, to enable it you have to do something like this:

```
echo 'Protocols h2 http/1.1' >> /etc/httpd/conf/httpd.conf
echo 'Protocols h2c http/1.1' >> /etc/httpd/conf/httpd.conf
```

I would leave that bit of configuration up to the person managing the system, no reason to have an example config seeing as how no other apache modules have example configs.

**Comment by b-harper** [comment]
@mmckinst, agreed.  Updated package will be hitting the testing repositories after tonight's automation run.

**Comment by Fale** [comment]
Any news on this? I'm testing it on multiple systems and I haven't found any issues

**Comment by b-harper** [comment]
Hello @Fale,

We were waiting on feedback before proceeding. Seeing that you gave feedback, we will proceed.  These package will hit the stable after tonight's automation run.
