### ISSUE TITLE
disable SSLv3 by default

### ISSUE THREAD

**Issue by carlwgeorge** [iuscommunity-pkg/httpd24u#8]
Currently the IUS mod_ssl (mod24u_ssl) package's default configuration leaves SSLv3 enabled.  This matches the current default behavior of the stock EL6 and EL7 mod_ssl packages.  Fedora explicitly disables SSLv3.  [We all know SSLv3 is bad](http://disablessl3.com).  Should the IUS mod_ssl package match the stock EL6/7 behavior for compatibility, or pursue a more secure default configuration?

**Comment by thebwt** [comment]
According to https://github.com/apache/httpd/blob/8322599c746bbdf1410a098a5d4764499baf7670/docs/conf/extra/httpd-ssl.conf.in it should be done already. 

Why are we changes the default configs at all? Shouldn't this be **I**nline **W**ith **U**pstream?

**Comment by carlwgeorge** [comment]
Upstream has multiple meanings.  There is obviously the upstream Apache HTTP Server project, but we also consider Fedora an upstream, because they take care of the hard work of fitting upstream software into the RPM-ecosystem (hence why we typically fork our initial spec files from Fedora).  That said, we often have to diverge from one or both upstreams in order to fit software into the EL environment (libraries, init systems, openssl ciphers, etc).  It is a balancing act.

I'm leaning towards following Fedora's lead on this and disabling SSLv3 by default (which they did because Apache upstream did it), but I wanted to open the public discussion for anyone to bring up concerns I haven't thought of.

**Comment by carlwgeorge** [comment]
Fixed in #15, will be released as [2.4.25-4](https://github.com/iuscommunity-pkg/httpd24u/releases/tag/2.4.25-4).
