### ISSUE TITLE
mod_http2 TLS support

### ISSUE THREAD

**Issue by carlwgeorge** [iuscommunity-pkg/httpd24u#9]
Currently RHEL doesn't ship a version of OpenSSL with the ALPN protocol.  HTTP2 connections can be negotiated over ALPN or the older NPN protocol.  However, the Apache mod_http2 module is only compatible with ALPN.  This means that currently, the IUS http24u packages only support HTTP2 over non-TLS connections.

Server configuration:
```
$ cat /etc/httpd/conf.d/http2.conf 
Protocols h2 h2c http/1.1
```
Client tests:
```
$ curl -s -I --http2 http://test7.ius.io | grep HTTP
HTTP/1.1 101 Switching Protocols
HTTP/2.0 200
```
```
$ curl -s -I --http2 https://test7.ius.io | grep HTTP
HTTP/1.1 200 OK
```

We believe that Red Hat [intends to rebase RHEL 7 OpenSSL to some version of 1.0.2](https://bugzilla.redhat.com/show_bug.cgi?id=1276310), which includes the ALPN protocol.  Unfortunately that appears to be planned for the 7.4 release.

**Comment by stylobille** [comment]
Hello,

As i said in the wishlist page, I really whish that you provide OpenSSL 1.0.2 with httpd. Currently there is no major reason to choose a really recent version of apache 2.4 except for the full http 2.0 support.

Providing packages with http 2.0 support would be a major reason to use the ius community repository, this would make it clearly more useful than the Red hat software collections beta program.

Redhat 7.4 will take at least a year before it comes out, so it wouldn't be wasted time to provide OpenSSL 1.0.2 until then.

Anyway I'm willing to test everything regarding http 2.0 if you provide the packages and I really hope you will :)

**Comment by carlwgeorge** [comment]
Howdy @stylobille,

We originally created the [httpd24u packages for EL6](https://bugs.launchpad.net/ius/+bug/1404930) due to the vastly improved support for using httpd with php-fpm.  Later it was requested that we [make those available for EL7](https://github.com/iuscommunity-pkg/httpd24u/issues/5) as well.

The latest [httpd24 Software Collection from Red Hat](https://www.softwarecollections.org/en/scls/rhscl/httpd24/) has [support for HTTP 2.0](https://bugzilla.redhat.com/show_bug.cgi?id=1276310#c17), albeit via the older NPN protocol ([which no longer works in Chrome](http://blog.chromium.org/2016/02/transitioning-from-spdy-to-http2.html)).  I opened this bug with the intention of researching if we can utilize the SCL patch to add NPN support to mod_http2, as a temporary measure until proper ALPN support is available.

I am adding a few more notes to the OpenSSL request to help clarify the problems with creating IUS packages for it.

We appreciate your offer to help test, we'll definitely take you up on that in the future, whether that is for a potential mod_http2 NPN patch or when RHEL 7.4 does eventually come out.

**Comment by carlwgeorge** [comment]
8d05b38 adds the patch from the httpd24 SCL to enable NPN support.  Initial tests appear to work.

```
$ curl -s -I --http2 https://test7.ius.io | grep HTTP
HTTP/2.0 200
```

The [2.4.20-3.ius](https://github.com/iuscommunity-pkg/httpd24u/releases/tag/2.4.20-3.ius) build will move to the testing repositories during tonight's automation.

**Comment by stylobille** [comment]
Great ! Much appreciated, I'll test that out :)

**Comment by stylobille** [comment]
No bugs seen this far, I made the update and it works like a charm.

**Comment by carlwgeorge** [comment]
Thanks for the feedback @stylobille.  I'm going to leave this one in testing for a few more days just in case anyone else wants to give it a shot.  I'll probably move it to stable on Monday.

**Comment by carlwgeorge** [comment]
This update will move to the stable repositories during tonight's automation.
